### PR TITLE
pass weights to the validation set as well

### PR DESCRIPTION
**Pull request by itamargolbary**
*Issue #144*

*Description of changes:*
when training using `csv_weights=1` , getting validation data with weights too.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by StephanieYuan** [comment]
Thank you for contributing! Changes lgtm, could you add some unit tests around it? Thanks!

**Comment by itamargolbary** [comment]
@StephanieYuan Thanks for your response!
I having some problems trying to run the tests. Do you know where can I find some guidance?
TY!

**Comment by edwardjkim** [comment]
@itamargolbary We will run some test and merge this PR in if test results look OK. If you already have unit tests, please feel free to add them to this PR before we merge this in or in a separate PR. Otherwise, we will take care of testing. Thanks for the PR!

**Comment by shugybugy-assaf** [comment]
TYVM @edwardjkim

**Pull request merged**
