### PR TITLE
Merge master into 0.90-2

### PR DESCRIPTION
**Pull request by aws-patlin**
Merge master into 0.90-2 to prepare for 1.0 release.

Merge conflicts fixed:
* requirements.txt modified
* ci/buildspec.yml removed

Testing:
Tox run successfully.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iyerr3** [comment]
I'm confused on why this is a PR? Shouldn't this be just a new branch creation.

**Comment by aws-patlin** [comment]
> I'm confused on why this is a PR? Shouldn't this be just a new branch creation.

We already have a 0.90-2 branch. I figured it would be better to merge master into that branch.

**Comment by iyerr3** [comment]
I think delete and create would be better as the `90-2` needs to be identical to master, isn't it?

**Comment by aws-patlin** [comment]
> I think delete and create would be better as the `90-2` needs to be identical to master, isn't it?

Ok, sounds good.

**Pull request closed without merging**
